#!/bin/sh
# Launched on the HOST at platform boot — starts the Realm with swtpm inside

REALM_KERNEL=/mnt/out/bin/Image
REALM_INITRD=/mnt/out-br/images/rootfs.cpio
LOGFILE=/var/log/realm-tpm.log

case "$1" in
  start)
    echo "Launching TPM Realm..."
    qemu-system-aarch64 \
      -M confidential-guest-support=rme0 \
      -object rme-guest,id=rme0,measurement-algorithm=sha512 \
      -nodefaults \
      -chardev stdio,mux=on,id=virtiocon0,signal=off \
      -device virtio-serial-pci \
      -device virtconsole,chardev=virtiocon0 \
      -mon chardev=virtiocon0,mode=readline \
      -kernel $REALM_KERNEL \
      -initrd $REALM_INITRD \
      -device virtio-net-pci,netdev=net0,romfile= \
      -netdev user,id=net0 \
      -cpu host -M virt -enable-kvm \
      -M gic-version=3,its=on \
      -smp 2 -m 512M -nographic >> $LOGFILE 2>&1
    ;;
  stop)
    killall qemu-system-aarch64
    ;;
esac
