#!/bin/sh
VTPM_DIR=/var/lib/swtpm-localca
SOCK=/run/swtpm.sock

case "$1" in
  start)
    mkdir -p $VTPM_DIR
    swtpm socket --tpm2 \
      --tpmstate dir=$VTPM_DIR \
      --ctrl type=unixio,path=$SOCK \
      --daemon --log level=0
    ;;
  stop)
    kill $(cat /run/swtpm.pid) 2>/dev/null
    ;;
esac
