#!/bin/sh
# devtmpfs does not get automounted for initramfs
/bin/mount -t devtmpfs devtmpfs /dev
/bin/mount -t proc proc /proc
/bin/mount -t 9p -o trans=virtio shr0 /mnt

# use the /dev/console device node from devtmpfs if possible to not
# confuse glibc's ttyname_r().
# This may fail (E.G. booted with console=), and errors from exec will
# terminate the shell, so use a subshell for the test
if (exec 0</dev/console) 2>/dev/null; then
    exec 0</dev/console
    exec 1>/dev/console
    exec 2>/dev/console
fi

if grep -q "initrd=rootfs.cpio" /proc/cmdline; then
    echo "Hello host!"
    /usr/bin/gen-run-vmm.sh
else
    echo "Hello Realm!"
    exec /sbin/init "$@"
fi
